# https://docs.gitlab.com/ee/install/docker/installation.html
version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: gitlab.example.com  # Change this to your domain or IP
    ports:
      - '80:80'   # HTTP
      #- '443:443' # HTTPS
      - '222:22'   # SSH
    volumes:
      - ./data:/var/opt/gitlab
      - ./logs:/var/log/gitlab
      - ./config:/etc/gitlab
    networks:
      - gitlab_network

# volumes:
#   gitlab-data:
#   gitlab-logs:
#   gitlab-config:

networks:
  gitlab_network:
    driver: bridge
