concurrent = 1
check_interval = 0

[[runners]]
  name = "gitlab-test"
  url = "https://gitlab.com/"
  token = "your-token"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "ubuntu:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    volumes = ["/cache"]
    networks = []