---
- name: Update Debian repository
  hosts: localhost
  become: yes
  tasks:
    - name: Update the package index
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Die Zeit, in der der Cache gültig ist (in Sekunden)
    - name: Upgrade all packages
      apt:
        upgrade: dist
