---
- name: Copy K3s kubeconfig to local machine
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/halim-dev/.kube/k3s.yaml
    flat: yes

- name: Ensure .kube directory exists on local machine
  local_action:
    module: file
    path: /home/halim-dev/.kube
    state: directory
    mode: '0700'

- name: Move and update K3s kubeconfig to .kube/config
  local_action:
    module: copy
    src: /home/halim-dev/.kube/k3s.yaml
    dest: /home/halim-dev/.kube/config
    remote_src: no
  become: true

- name: Update kubeconfig server address
  local_action:
    module: lineinfile
    path: /home/halim-dev/.kube/config
    regexp: '^(\s*server:\s*)https://127.0.0.1:6443'
    line: '\1https://172.15.2.22:6443'
