---
# Tasks for installing K3s server on control nodes

- name: Download and install K3s server with external MySQL
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 K3S_DATASTORE_ENDPOINT="mysql://{{ mysql_user }}:{{ mysql_password }}@tcp({{ mysql_host }}:{{ mysql_port }})/{{ mysql_database }}" " sh -
  args:
    creates: /usr/local/bin/k3s

- name: Get node token
  command: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_node_token

- name: Debug node token
  debug:
    msg: "Node token is {{ k3s_node_token.stdout }}"
