---
# Tasks for installing K3s agent on worker nodes

- name: Set K3s server IPs
  set_fact:
    k3s_server_ip: "{{ groups['control'][0] | extract(hostvars, 'ansible_host') }}"

- name: Install K3s agent
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL="https://{{ k3s_server_ip }}:6443" K3S_TOKEN="{{ hostvars[groups['control'][0]].k3s_node_token.stdout }}" sh -
  args:
    creates: /usr/local/bin/k3s-agent

- name: Ensure K3s agent is running
  systemd:
    name: k3s-agent
    state: started
    enabled: yes
